public with sharing class OpportunityConstants {

    // This value is set based on a requirement from the MRA department.  If this changes, this
    // needs to be taken into consideration.
    public static final Integer DEFAULT_DAYS_TO_CLOSE = 30;

    public static final String STAGE_ASSIGNED = 'Assigned';
    public static final String STAGE_COMPLETE = 'Complete';
    public static final String STAGE_DECLINED = 'Declined';
    public static final String STAGE_MEMBER_REJECTED = 'Member Rejected';
    public static final String STAGE_NEW = 'New';
    public static final String STAGE_NO_FURTHER_ACTION = 'No Further Action';

}