public class RecordTypeConstants {
    public static final String ACCOUNT_DEFAULT = 'Default';
    public static final String ACCOUNT_DNA = 'DNA';

    public static final String CASE_DEFAULT = 'Default';
    public static final String CASE_MEMBER_SUPPORT = 'Member Support';
    public static final String CASE_ONLINE_ACCOUNT_OPENING = 'Online Account Opening';

    public static final String CONTACT_DEFAULT = 'Default';
    public static final String CONTACT_DNA = 'DNA';

    public static final String LEAD_DEFAULT = 'Default';
    public static final String LEAD_MCC_REFERRAL = 'MCC Referral';

    public static final String OPPORTUNITY_DEFAULT = 'Default';
    public static final String OPPORTUNITY_DEPOSIT_PRODUCT = 'Deposit Product';
    public static final String OPPORTUNITY_HELOC = 'HELOC';
    public static final String OPPORTUNITY_LOAN = 'Loan';
    public static final String OPPORTUNITY_PROSPECT = 'Prospect';
}